import Header from './_components/Header'
import Navbar from './_components/Navbar'
import './globals.css'
import { Montserrat } from 'next/font/google'
import dynamic from 'next/dynamic'

const Footer = dynamic(() => import('./_components/Footer'))

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'MMN & JTSE Toll',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className='sticky z-50 top-0 w-full'>
          <Header />
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
