import { Montserrat } from 'next/font/google'
import '../globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'MMN & JTSE Toll',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className='flex flex-col justify-center w-full h-[100vh] bg-[#D7D7D7]'>
          {children}
        </div>
      </body>
    </html>
  )
}
